button_text: 
  type: string
  default: ""
  
button_URL: 
  type: string
  default: "/"

mobile_button_text: 
  type: string
  default: ""
  description: optional alternative text for screens under 550px wide<br/> If you want to hide the button on mobile entirely enter&colon; none

button_text_color: 
  type: string
  default: ""
  description: optional

button_background_color: 
  type: string
  default: ""
  description: optional

button_hover_text_color: 
  type: string
  default: ""
  description: optional

button_hover_background_color: 
  type: string
  default: ""
  description: optional

